### ISSUE TITLE
生成的垃圾文件只能生成一个或几个就会报错

### ISSUE THREAD

**Issue by shizu2014** [834519342/oc-confuse#3]
添加路径：/Users/ios/Downloads/oc-confuse-master 3/JunkFiles/negate
创建文件：repeal.plist
创建文件：restate.jpg
Traceback (most recent call last):
  File "JunkFile_maker.py", line 204, in <module>
    add_file_to_folder(os.path.join(parent, folder))
  File "JunkFile_maker.py", line 169, in add_file_to_folder
    get_one_file(os.path.join(folder_path, file_name), f_type)
  File "JunkFile_maker.py", line 149, in get_one_file
    get_image_text(file_path)
  File "JunkFile_maker.py", line 141, in get_image_text
    misc.imsave(file_path, img)
AttributeError: 'module' object has no attribute 'imsave'

**Comment by 834519342** [comment]
Python报错module 'scipy.misc' has no attribute 'imresize'

Python报错module 'scipy.misc' has no attribute 'imsave'

此类的报错，可安装 Pillow 解决

pip install  Pillow

或pip3 install  Pillow
————————————————
版权声明：本文为CSDN博主「u014516174」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u014516174/java/article/details/84998967

**Comment by shizu2014** [comment]
嗯 最好在文档中注明需要的依赖。。提个建议哈
